version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: payment_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payments_db
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    volumes:
      - mysql_data:/var/lib/mysql

  gateways-mock:
    image: matheusprotzen/gateways-mock
    container_name: payment_gateways_mock
    restart: always
    ports:
      - '3001:3001'
      - '3002:3002'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments-processing_api
    restart: unless-stopped
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=api_user
      - DB_PASSWORD=api_password
      - DB_DATABASE=payments_db
      - GATEWAY1_URL=http://gateways-mock:3001
      - GATEWAY2_URL=http://gateways-mock:3002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql-db
      - gateways-mock

volumes:
  mysql_data:
