openapi: 3.0.0
info:
  title: API Multi-Gateways de Pagamento
  version: 1.0.0
  description: API para gerenciamento de pagamentos com múltiplos gateways.

paths:
  /api/login:
    post:
      summary: Realiza o login do usuário
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: admin@be.tech
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Login realizado com sucesso. Retorna o Access Token.
        '401':
          description: Credenciais inválidas.
        '422':
          description: Erro na validação dos dados de entrada.
